// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatchPanda.Web.Db;

#nullable disable

namespace PatchPanda.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251023143838_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AppVersionContainer", b =>
                {
                    b.Property<int>("ApplicationsId")
                        .HasColumnType("int");

                    b.Property<int>("NewerVersionsId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationsId", "NewerVersionsId");

                    b.HasIndex("NewerVersionsId");

                    b.ToTable("AppVersionContainer");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.AppVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Breaking")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Notified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Prerelease")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AppVersions");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.ComposeStack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigFile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StackName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Stacks");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentSha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GitHubRepo")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSecondary")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastVersionCheck")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MultiContainerAppId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Regex")
                        .HasColumnType("longtext");

                    b.Property<string>("SecondaryGitHubRepos")
                        .HasColumnType("longtext");

                    b.Property<int>("StackId")
                        .HasColumnType("int");

                    b.Property<string>("TargetImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Uptime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Version")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MultiContainerAppId");

                    b.HasIndex("StackId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.MultiContainerApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MultiContainerApps");
                });

            modelBuilder.Entity("AppVersionContainer", b =>
                {
                    b.HasOne("PatchPanda.Web.Entities.Container", null)
                        .WithMany()
                        .HasForeignKey("ApplicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatchPanda.Web.Entities.AppVersion", null)
                        .WithMany()
                        .HasForeignKey("NewerVersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.Container", b =>
                {
                    b.HasOne("PatchPanda.Web.Entities.MultiContainerApp", "MultiContainerApp")
                        .WithMany("Containers")
                        .HasForeignKey("MultiContainerAppId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PatchPanda.Web.Entities.ComposeStack", "Stack")
                        .WithMany("Apps")
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MultiContainerApp");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.ComposeStack", b =>
                {
                    b.Navigation("Apps");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.MultiContainerApp", b =>
                {
                    b.Navigation("Containers");
                });
#pragma warning restore 612, 618
        }
    }
}
